# Generated by Django 4.1 on 2022-08-17 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioDeContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(max_length=11)),
                ('forma_de_contato', models.CharField(choices=[('Em', 'E-mail'), ('Tf', 'Telefone'), ('Wp', 'Whatsapp'), ('Tg', 'Telegram')], max_length=20)),
                ('tipo_de_projeto', models.CharField(choices=[('Site', 'Site'), ('App', 'App'), ('Análise de Dados', 'Análise de Dados')], max_length=20)),
                ('qual_o_seu_orçamento', models.CharField(blank=True, choices=[('0-1', '0 - 1.000'), ('1-5', '1.000 - 5.000'), ('5-a', '5.000 - acima')], max_length=20, null=True)),
                ('descrição_do_projeto', models.TextField(max_length=5000)),
                ('data_de_publicação', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Publicação')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_do_icons_de_redes_sociais', models.CharField(blank=True, default='black', max_length=50, null=True)),
                ('cor_secundaria_do_icons_de_redes_sociais', models.CharField(blank=True, default='black', max_length=50, null=True)),
                ('cor_dos_icons_de_contato', models.CharField(blank=True, default='black', max_length=50, null=True)),
                ('cor_secundaria_dos_icons_de_contato', models.CharField(blank=True, default='black', max_length=50, null=True)),
                ('cor_dos_detalhes', models.CharField(blank=True, default='black', max_length=50, null=True)),
                ('cor_do_botão', models.CharField(blank=True, default='black', max_length=50, null=True)),
                ('cor_secundaria_do_botão', models.CharField(blank=True, default='black', max_length=50, null=True)),
                ('footer', models.FileField(blank=True, null=True, upload_to='site/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('profissão', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('hero', models.FileField(blank=True, null=True, upload_to='sobre/images/')),
                ('perfil_imagem', models.FileField(blank=True, null=True, upload_to='sobre/images/')),
                ('background_depoimento', models.FileField(blank=True, null=True, upload_to='sobre/images/')),
                ('sobre_frase', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='portfólio',
            name='capa',
            field=models.FileField(blank=True, default='portfólio/images/Em-Breve.jpg', null=True, upload_to='portfólio/images/'),
        ),
        migrations.AddField(
            model_name='portfólio',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Site', 'Site'), ('App', 'App'), ('Análise de Dados', 'Análise de Dados')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='portfólio',
            name='cliente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portfólio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='portfólio',
            name='data_de_publicação',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Publicação'),
        ),
        migrations.AddField(
            model_name='portfólio',
            name='descrição',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='portfólio',
            name='github',
            field=models.CharField(blank=True, default='github', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portfólio',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portfólio',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='portfólio',
            name='url_do_projeto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SobreHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.CharField(blank=True, max_length=50, null=True)),
                ('porcentagem', models.CharField(blank=True, max_length=50, null=True)),
                ('add_habilidade', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.sobre')),
            ],
        ),
        migrations.CreateModel(
            name='SobreDepoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depoimento_cliente', models.CharField(blank=True, default='Nome', max_length=50, null=True)),
                ('depoimento_tipo_de_projeto', models.CharField(blank=True, default='Freelance', max_length=50, null=True)),
                ('depoimento', models.TextField(blank=True, default='Descrição', max_length=1000, null=True)),
                ('depoimentos_imagem', models.FileField(blank=True, null=True, upload_to='sobre/images/')),
                ('add_depoimento', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.sobre')),
            ],
        ),
        migrations.CreateModel(
            name='PortfólioImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='portfólio/images/')),
                ('add_imagem', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.portfólio')),
            ],
        ),
        migrations.CreateModel(
            name='ContatoRedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rede_social', models.CharField(blank=True, default='instagram', max_length=50, null=True)),
                ('url', models.CharField(blank=True, default='https://www.instagram.com/samuelbarbosa_dev/', max_length=500, null=True)),
                ('add_redeSocial', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.contato')),
            ],
        ),
    ]
