# Generated by Django 4.1 on 2022-08-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_contato_formulariodecontato_site_sobre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatoredesocial',
            name='rede_social',
            field=models.CharField(blank=True, default='rede social', max_length=50, null=True),
        ),
    ]
