# Generated by Django 4.1 on 2022-08-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_alter_contatoredesocial_rede_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatoredesocial',
            name='rede_social',
            field=models.CharField(blank=True, choices=[('twitter', 'twitter'), ('instagram', 'instagram'), ('whatsapp', 'whatsapp'), ('telegram', 'telegram'), ('behance', 'behance'), ('twitch', 'twitch'), ('github', 'github'), ('linkedin', 'linkedin'), ('reddit', 'reddit'), ('diagram-2-fill', 'diagram-2-fill')], default='diagram-2-fill', max_length=50, null=True),
        ),
    ]
