# Generated by Django 4.1 on 2022-08-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_alter_contatoredesocial_rede_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariodecontato',
            name='tipo_de_projeto',
            field=models.CharField(max_length=30),
        ),
    ]
