# Generated by Django 4.1 on 2022-08-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_alter_formulariodecontato_tipo_de_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobre',
            name='perfil_imagem',
        ),
        migrations.AddField(
            model_name='sobre',
            name='foto_de_perfil',
            field=models.FileField(blank=True, default='default/images/foto_de_perfil.svg', null=True, upload_to='sobre/images/'),
        ),
        migrations.AlterField(
            model_name='site',
            name='footer',
            field=models.FileField(blank=True, default='default/images/footer.webp', null=True, upload_to='site/images/'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='background_depoimento',
            field=models.FileField(blank=True, default='default/images/backgroud.jpg', null=True, upload_to='sobre/images/'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='email',
            field=models.EmailField(blank=True, default='Qual é o seu email?', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='hero',
            field=models.FileField(blank=True, default='default/images/hero.webp', null=True, upload_to='sobre/images/'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='nome',
            field=models.CharField(blank=True, default='Qual é o seu nome?', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='profissão',
            field=models.CharField(blank=True, default='Qual é sua profissão?', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='sobre_frase',
            field=models.CharField(blank=True, default='Qual é a sua frase?', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='telefone',
            field=models.CharField(blank=True, default='Qual é o seu telefone?', max_length=11, null=True),
        ),
    ]
