# Generated by Django 4.1 on 2022-08-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_alter_site_footer_alter_sobre_background_depoimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfólio',
            name='capa',
            field=models.FileField(default='portfólio/images/Em-Breve.jpg', upload_to='portfólio/images/'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='background_depoimento',
            field=models.FileField(default='sobre/images/backgroud.jpg', upload_to='sobre/images/'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='foto_de_perfil',
            field=models.FileField(default='sobre/images/foto_de_perfil.svg', upload_to='sobre/images/'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='hero',
            field=models.FileField(default='sobre/images/hero.webp', upload_to='sobre/images/'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='sobre_frase',
            field=models.CharField(default='Qual é a sua frase?', max_length=50),
        ),
    ]
