# Generated by Django 4.1 on 2022-08-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0008_alter_portfólio_capa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfólio',
            name='capa',
            field=models.FileField(blank=True, default='portfólio/images/Em-Breve.jpg', null=True, upload_to='portfólio/images/'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='background_depoimento',
            field=models.FileField(blank=True, default='sobre/images/backgroud.jpg', null=True, upload_to='sobre/images/'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='foto_de_perfil',
            field=models.FileField(blank=True, default='sobre/images/foto_de_perfil.svg', null=True, upload_to='sobre/images/'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='hero',
            field=models.FileField(blank=True, default='sobre/images/hero.webp', null=True, upload_to='sobre/images/'),
        ),
    ]
