# Generated by Django 4.1 on 2022-08-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0010_alter_portfólio_capa_alter_site_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre',
            name='background_depoimento',
            field=models.FileField(default='default/images/backgroud.jpg', upload_to='sobre/images/'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='foto_de_perfil',
            field=models.FileField(default='default/images/foto_de_perfil.svg', upload_to='sobre/images/'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='hero',
            field=models.FileField(default='default/images/hero.webp', upload_to='sobre/images/'),
        ),
    ]
