# Generated by Django 4.1 on 2022-08-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0011_alter_sobre_background_depoimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='footer',
            field=models.FileField(default='default/images/footer.webp', upload_to='site/images/'),
        ),
    ]
