# Generated by Django 4.1 on 2022-08-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0012_alter_site_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobredepoimento',
            name='depoimentos_imagem',
            field=models.FileField(blank=True, default='default/images/depoimentos_imagem.png', null=True, upload_to='sobre/images/'),
        ),
    ]
