# Generated by Django 4.1 on 2022-08-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0013_alter_sobredepoimento_depoimentos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfólio',
            name='categoria',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
