# Generated by Django 4.1 on 2022-08-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0014_alter_portfólio_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfólio',
            name='github',
        ),
    ]
