# Generated by Django 4.1 on 2022-08-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0015_remove_portfólio_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfólio',
            name='depoimento_do_cliente',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
