# Generated by Django 4.1 on 2022-08-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0016_portfólio_depoimento_do_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfólio',
            name='imagem_do_cliente',
            field=models.FileField(blank=True, default='default/images/depoimentos_imagem.png', null=True, upload_to='sobre/images/'),
        ),
    ]
