# Generated by Django 4.1 on 2022-08-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0017_portfólio_imagem_do_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfólio',
            name='capa',
            field=models.FileField(default='default/images/Em-Breve.jpg', upload_to='portfólio/images/'),
        ),
        migrations.AlterField(
            model_name='portfólio',
            name='imagem_do_cliente',
            field=models.FileField(default='default/images/depoimentos_imagem.png', upload_to='sobre/images/'),
        ),
        migrations.AlterField(
            model_name='sobredepoimento',
            name='depoimentos_imagem',
            field=models.FileField(default='default/images/depoimentos_imagem.png', upload_to='sobre/images/'),
        ),
    ]
