# Generated by Django 4.1 on 2022-08-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0018_alter_portfólio_capa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfólio',
            name='frase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='portfólio',
            name='categoria',
            field=models.CharField(default='categoria', max_length=30),
        ),
        migrations.AlterField(
            model_name='portfólio',
            name='titulo',
            field=models.CharField(default='titulo', max_length=50),
        ),
    ]
