# Generated by Django 4.1 on 2022-08-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0020_alter_portfólio_frase'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
