# Generated by Django 4.1 on 2022-08-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0023_rename_forma_de_contato_formulariodecontato_forma_de_contato_preferencial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='nome',
            field=models.CharField(blank=True, default='Nome', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='background_depoimento',
            field=models.FileField(default='default/images/backgroud.webp', upload_to='sobre/images/'),
        ),
    ]
