# Generated by Django 4.1 on 2022-08-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0024_site_nome_alter_sobre_background_depoimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfólio',
            old_name='capa',
            new_name='capa_do_projeto',
        ),
        migrations.RenameField(
            model_name='sobre',
            old_name='sobre_frase',
            new_name='frase',
        ),
    ]
