# Generated by Django 4.1 on 2022-08-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0025_rename_capa_portfólio_capa_do_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='frase',
            field=models.CharField(blank=True, default='Nome', max_length=100, null=True),
        ),
    ]
