# Generated by Django 4.1 on 2022-08-21 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0026_site_frase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfólioimagem',
            name='add_imagem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adm.portfólio'),
        ),
    ]
