# Generated by Django 4.1 on 2022-08-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0027_alter_portfólioimagem_add_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfólio',
            name='imagem_do_cliente',
            field=models.FileField(default='default/images/depoimentos_imagem.png', upload_to='portfólio/images/'),
        ),
    ]
