# Generated by Django 4.1 on 2022-08-22 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0030_alter_formulariodecontato_telefone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfólioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='categoria', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='portfólio',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm.portfóliocategoria'),
        ),
    ]
