# Generated by Django 4.1 on 2022-08-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0031_portfóliocategoria_alter_portfólio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfólio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm.portfóliocategoria'),
        ),
    ]
