# Generated by Django 4.1 on 2022-08-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0032_alter_portfólio_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfóliocategoria',
            old_name='nome',
            new_name='categoria',
        ),
    ]
