# Generated by Django 4.1 on 2022-08-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0033_rename_nome_portfóliocategoria_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SobreDepoimento',
        ),
    ]
