# Generated by Django 4.1 on 2022-08-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0034_delete_sobredepoimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='icon_150x150',
            field=models.FileField(default='default/images/onda_icon_maior.png', upload_to='site/images/'),
        ),
        migrations.AddField(
            model_name='site',
            name='icon_32x32',
            field=models.FileField(default='default/images/onda_icon.png', upload_to='site/images/'),
        ),
    ]
