# Generated by Django 4.1 on 2022-08-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0035_site_icon_150x150_site_icon_32x32'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='cor_do_botão',
        ),
        migrations.RemoveField(
            model_name='site',
            name='cor_do_icons_de_redes_sociais',
        ),
        migrations.RemoveField(
            model_name='site',
            name='cor_dos_detalhes',
        ),
        migrations.RemoveField(
            model_name='site',
            name='cor_dos_icons_de_contato',
        ),
        migrations.RemoveField(
            model_name='site',
            name='cor_secundaria_do_botão',
        ),
        migrations.RemoveField(
            model_name='site',
            name='cor_secundaria_do_icons_de_redes_sociais',
        ),
        migrations.RemoveField(
            model_name='site',
            name='cor_secundaria_dos_icons_de_contato',
        ),
    ]
