# Generated by Django 4.1 on 2022-08-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0036_remove_site_cor_do_botão_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='titulo_do_formulario',
            field=models.CharField(blank=True, default='Fale comigo.', max_length=30, null=True),
        ),
    ]
